### ISSUE TITLE
My bug

### ISSUE THREAD

**Issue by k3hgyk92** [armsnyder/terraform-provider-gitlab#39]
Oh gosh I have a problem

```
panic: value is marked, so must be unmarked first

goroutine 97 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.AsString(0x38e7980, 0xc000052459, 0x31b1c40, 0xc000a409e0, 0x38e7901, 0xc000052459)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/value_ops.go:1249 +0x4f
github.com/hashicorp/hcl/v2.Index(0x38e7a80, 0xc0001a1380, 0x30b9460, 0xc0005ce060, 0x38e7980, 0xc000052459, 0x31b1c40, 0xc000a409e0, 0xc0001b6880, 0x0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.2/ops.go:146 +0x105b
github.com/hashicorp/hcl/v2/hclsyntax.(*IndexExpr).Value(0xc0001b67e0, 0xc000a408c0, 0x0, 0xc000a3b800, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.2/hclsyntax/expression.go:711 +0x27d
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc000668f00, 0x38e6540, 0xc0001b67e0, 0x38e79c0, 0x4a00200, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:171 +0x1b7
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc0005a8ea0, 0x38e6540, 0xc0001b67e0, 0x38e79c0, 0x4a00200, 0x0, 0x0, 0x0, 0x1068156, 0x106d420, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:287 +0xbb
github.com/hashicorp/terraform/terraform.(*NodeLocal).Execute(0xc000a44690, 0x3923940, 0xc0005a8ea0, 0xc00003a002, 0x3108040, 0x328f6a0)
	/home/circleci/project/project/terraform/node_local.go:156 +0x71d
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000678a90, 0x3923940, 0xc0005a8ea0, 0x72cfb58, 0xc000a44690, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x328f6a0, 0xc000a44690, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0006648a0, 0x328f6a0, 0xc000a44690, 0xc00070c740)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x1246
panic: value is marked, so must be unmarked first

goroutine 97 [running]:
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/marks.go:123
github.com/zclconf/go-cty/cty.Value.AsString(0x38e7980, 0xc000052459, 0x31b1c40, 0xc000a409e0, 0x38e7901, 0xc000052459)
	/go/pkg/mod/github.com/zclconf/go-cty@v1.7.1/cty/value_ops.go:1249 +0x4f
github.com/hashicorp/hcl/v2.Index(0x38e7a80, 0xc0001a1380, 0x30b9460, 0xc0005ce060, 0x38e7980, 0xc000052459, 0x31b1c40, 0xc000a409e0, 0xc0001b6880, 0x0, ...)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.2/ops.go:146 +0x105b
github.com/hashicorp/hcl/v2/hclsyntax.(*IndexExpr).Value(0xc0001b67e0, 0xc000a408c0, 0x0, 0xc000a3b800, 0x1, 0x1, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.8.2/hclsyntax/expression.go:711 +0x27d
github.com/hashicorp/terraform/lang.(*Scope).EvalExpr(0xc000668f00, 0x38e6540, 0xc0001b67e0, 0x38e79c0, 0x4a00200, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/circleci/project/project/lang/eval.go:171 +0x1b7
github.com/hashicorp/terraform/terraform.(*BuiltinEvalContext).EvaluateExpr(0xc0005a8ea0, 0x38e6540, 0xc0001b67e0, 0x38e79c0, 0x4a00200, 0x0, 0x0, 0x0, 0x1068156, 0x106d420, ...)
	/home/circleci/project/project/terraform/eval_context_builtin.go:287 +0xbb
github.com/hashicorp/terraform/terraform.(*NodeLocal).Execute(0xc000a44690, 0x3923940, 0xc0005a8ea0, 0xc00003a002, 0x3108040, 0x328f6a0)
	/home/circleci/project/project/terraform/node_local.go:156 +0x71d
github.com/hashicorp/terraform/terraform.(*ContextGraphWalker).Execute(0xc000678a90, 0x3923940, 0xc0005a8ea0, 0x72cfb58, 0xc000a44690, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph_walk_context.go:127 +0xbc
github.com/hashicorp/terraform/terraform.(*Graph).walk.func1(0x328f6a0, 0xc000a44690, 0x0, 0x0, 0x0)
	/home/circleci/project/project/terraform/graph.go:59 +0x962
github.com/hashicorp/terraform/dag.(*Walker).walkVertex(0xc0006648a0, 0x328f6a0, 0xc000a44690, 0xc00070c740)
	/home/circleci/project/project/dag/walk.go:387 +0x375
created by github.com/hashicorp/terraform/dag.(*Walker).Update
	/home/circleci/project/project/dag/walk.go:309 +0x1246



!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.log" file that was created may contain 
sensitive information that must be redacted before it is safe to share 
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by k3hgyk92** [comment]
My response

**Comment by armsnyder** [comment]
I definitely fixed it
